### ISSUE TITLE
Error Launch Power BI Reports 

### ISSUE THREAD

**Issue by pryazarias** [microsoft/SqlNexus#73] opened 2018-08-10 18:06 UTC
See the end of this message for details on how to call the
just-in-time (JIT) debugging instead of this dialog box.

************** Texto de Exceção **************
System.ComponentModel.Win32Exception (0x80004005): The system can not find the file specified
   em System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   em System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   em sqlnexus.Globals.LuanchPowerBI() na C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\Globals.cs:linha 92
   em System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   em System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.Label.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Uploaded Assemblies **************
mscorlib
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.3130.0 built by: NET472REL1LAST_B
    Base de Código: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
sqlnexus
    Versão do Assembly: 6.0.0.8
    Versão do Win32: 6.0.0.8
    Base de Código: file:///C:/Users/Desktop/Tools/SQLNexus.6.0.0.8/sqlnexus.exe
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NexusInterfaces
    Versão do Assembly: 6.0.0.8
    Versão do Win32: 6.0.0.8
    Base de Código: file:///C:/Users/Desktop/Tools/SQLNexus.6.0.0.8/NexusInterfaces.DLL
----------------------------------------
Microsoft.ReportViewer.WinForms
    Versão do Assembly: 13.0.0.0
    Versão do Win32: 13.0.1601.5
    Base de Código: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.ReportViewer.WinForms/13.0.0.0__89845dcd8080cc91/Microsoft.ReportViewer.WinForms.dll
----------------------------------------
System.Data
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2633.0 built by: NET471REL1LAST_C
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2670.0 built by: NET471REL1LAST_C
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2612.0 built by: NET471REL1LAST_B
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.ServiceProcess
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
Microsoft.ReportViewer.WinForms.resources
    Versão do Assembly: 13.0.0.0
    Versão do Win32: 13.0.1601.5
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.ReportViewer.WinForms.resources/v4.0_13.0.0.0_pt_89845dcd8080cc91/Microsoft.ReportViewer.WinForms.resources.dll
----------------------------------------
Microsoft.ReportViewer.Common
    Versão do Assembly: 13.0.0.0
    Versão do Win32: 13.0.1601.5
    Base de Código: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.ReportViewer.Common/13.0.0.0__89845dcd8080cc91/Microsoft.ReportViewer.Common.dll
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Deployment
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Deployment.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment.resources/v4.0_4.0.0.0_pt-BR_b03f5f7f11d50a3a/System.Deployment.resources.dll
----------------------------------------
System.Data.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Data.resources.dll
----------------------------------------
System.Transactions
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.VisualBasic
    Versão do Assembly: 10.0.0.0
    Versão do Win32: 14.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Microsoft.SqlServer.Types
    Versão do Assembly: 13.0.0.0
    Versão do Win32: 2015.0130.1601.05 ((SQL16_RTM).160429-2226)
    Base de Código: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.SqlServer.Types/13.0.0.0__89845dcd8080cc91/Microsoft.SqlServer.Types.dll
----------------------------------------
Microsoft.ReportViewer.Common.resources
    Versão do Assembly: 13.0.0.0
    Versão do Win32: 13.0.1601.5
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.ReportViewer.Common.resources/v4.0_13.0.0.0_pt_89845dcd8080cc91/Microsoft.ReportViewer.Common.resources.dll
----------------------------------------
Microsoft.ReportViewer.ProcessingObjectModel
    Versão do Assembly: 13.0.0.0
    Versão do Win32: 13.0.1601.5
    Base de Código: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.ReportViewer.ProcessingObjectModel/13.0.0.0__89845dcd8080cc91/Microsoft.ReportViewer.ProcessingObjectModel.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.7.2556.0 built by: NET471REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by vahidammary** [comment] 2019-01-23 12:47
hej I'm new here and any solution for this problem?

**Comment by johnmart82** [comment] 2019-07-30 12:36
Done some digging on this and it seems that the PBIT file that nexus is trying to load is not included in the release or the repo that I can see. Does anyone know where the file is?

**Comment by ram2ybabu** [comment] 2021-01-27 09:41
The issue is fixed now. All .pbit files are shipped with latest nexus

**Closed by ram2ybabu** 2021-01-27 09:41 UTC
